SUPABASE_URL = "https://github.com/anandnehra08/save-dashboard/blob/main/.streamlit/secrets.toml"
SUPABASE_SERVICE_ROLE_KEY =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZXJqeWJnZmVhZGZ2d2hjYXNrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjUyOTc2NiwiZXhwIjoyMTAyMTA1NzY2fQ.zDAcro5tnZVdS7KFzUUTODKyeZUovcgyFi0cKADUykc"
