SUPABASE_URL = "https://rderjybgfeadfvwhcask.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZXJqeWJnZmVhZGZ2d2hjYXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1Mjk3NjYsImV4cCI6MjEwMjEwNTc2Nn0.7EIGMgsByz9Ow-6C-d_28kWDmNidNaMMJYNiyKgG6nw"

FAST2SMS_API_KEY = "आपकी_Fast2SMS_Dev_API_Key"
